<?php

declare(strict_types=1);

namespace JsbParser\Contracts;

/**
 * Interface for parsing JSB Leaders.htm files.
 *
 * The Leaders.htm file contains individual awards, stat leaders, and team selections
 * generated by the Jump Shot Basketball simulation engine.
 */
interface LeadersHtmParserInterface
{
    /**
     * Parse a Leaders.htm file into structured award data.
     *
     * @param string $filePath Path to the Leaders.htm file
     * @return array{
     *   individual: array<string, list<string>>,
     *   stat_leaders: array<string, list<array{name: string, stat: string}>>,
     *   teams: array<string, list<string>>
     * }
     * @throws \RuntimeException If file cannot be read or has invalid structure
     */
    public static function parseFile(string $filePath): array;
}
