-- Expand ibl_plr_snapshots to capture ALL data from .plr files.
--
-- Previously only ratings, attributes, contract, depth chart, and physical
-- attributes were stored (~49 columns). This adds season stats, career stats,
-- game highs, real-life stats, preference weights, draft info, derived fields,
-- playoff stats (speculative, from offset gap 208-267), and raw unknown gap data.

-- Season stats (regular season, from offsets 144-207)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `ordinal`          SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_gs`         SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_gm`         SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_min`        MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_fgm`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_fga`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_ftm`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_fta`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_3gm`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_3ga`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_orb`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_drb`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_ast`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_stl`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_to`         SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_blk`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_pf`         SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_reb`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `stats_pts`        SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Playoff season stats (speculative — offsets 208-267, mirrors season stats minus games started)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `po_stats_gm`      SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_min`     MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_2gm`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_2ga`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_ftm`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_fta`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_3gm`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_3ga`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_orb`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_drb`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_ast`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_stl`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_tvr`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_blk`     SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `po_stats_pf`      SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Career stats (offsets 437-511)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `car_gm`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_min`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_fgm`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_fga`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_ftm`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_fta`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_tgm`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_tga`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_orb`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_drb`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_reb`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_ast`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_stl`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_to`           MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_blk`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_pf`           MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `car_pts`          MEDIUMINT UNSIGNED NOT NULL DEFAULT 0;

-- Season highs (offsets 341-354)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `sh_pts`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sh_reb`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sh_ast`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sh_stl`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sh_blk`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `s_dd`             SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `s_td`             SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Playoff highs (offsets 355-364)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `sp_pts`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sp_reb`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sp_ast`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sp_stl`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `sp_blk`           SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Career season highs (offsets 365-406)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `ch_pts`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `ch_reb`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `ch_ast`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `ch_stl`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `ch_blk`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `c_dd`             SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `c_td`             SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Career playoff highs (offsets 407-436)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `cp_pts`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `cp_reb`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `cp_ast`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `cp_stl`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `cp_blk`           SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Real-life stats (offsets 52-111, rl_ prefix is new — ibl_plr doesn't store these)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `rl_gp`            SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_min`           MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_fgm`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_fga`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_ftm`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_fta`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_3gm`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_3ga`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_orb`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_drb`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_ast`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_stl`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_tvr`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_blk`           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rl_pf`            SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Preference weights (offsets 274-285)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `coach`            TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `loyalty`          TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN `playingTime`      TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN `winner`           TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN `tradition`        TINYINT NOT NULL DEFAULT 0,
  ADD COLUMN `security`         TINYINT NOT NULL DEFAULT 0;

-- Draft info (offsets 326-330)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `draftround`       TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `draftpickno`      TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `fa_signing_flag`  TINYINT(1) NOT NULL DEFAULT 0;

-- Other fields
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `dc_canPlayInGame` TINYINT NOT NULL DEFAULT 1,
  ADD COLUMN `injured`          SMALLINT UNSIGNED NOT NULL DEFAULT 0;

-- Derived fields
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `draftyear`        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `salary`           SMALLINT NOT NULL DEFAULT 0;

-- Unknown gap: offsets 112-127 (16 bytes = 8 × 2-byte fields)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `unk_112` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_114` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_116` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_118` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_120` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_122` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_124` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_126` SMALLINT NOT NULL DEFAULT 0;

-- Unknown gap: offset 138-139 (2 bytes)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `unk_138` SMALLINT NOT NULL DEFAULT 0;

-- Unknown gap: offsets 294-297 (4 bytes = 2 × 2-byte fields)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `unk_294` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_296` SMALLINT NOT NULL DEFAULT 0;

-- Unknown gap: offsets 322-325 (4 bytes = 2 × 2-byte fields)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `unk_322` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_324` SMALLINT NOT NULL DEFAULT 0;

-- Unknown gap: offsets 331-340 (10 bytes = 5 × 2-byte fields)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `unk_331` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_333` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_335` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_337` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_339` SMALLINT NOT NULL DEFAULT 0;

-- Unknown gap: offsets 512-549 (38 bytes = 19 × 2-byte fields)
ALTER TABLE `ibl_plr_snapshots`
  ADD COLUMN `unk_512` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_514` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_516` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_518` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_520` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_522` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_524` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_526` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_528` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_530` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_532` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_534` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_536` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_538` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_540` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_542` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_544` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_546` SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN `unk_548` SMALLINT NOT NULL DEFAULT 0;
