<?php

declare(strict_types=1);

namespace Trading;

use Trading\Contracts\CashTransactionHandlerInterface;

/**
 * CashTransactionHandler - Handles cash considerations in trades
 *
 * Manages the creation of cash entries in trades including generating unique
 * player IDs for cash transactions and creating the paired positive/negative
 * cash records for trading teams.
 * 
 * @see CashTransactionHandlerInterface
 */
class CashTransactionHandler implements CashTransactionHandlerInterface
{
    protected object $db;
    protected TradingRepository $repository;
    protected \Services\CommonMysqliRepository $commonRepository;

    public function __construct(object $db, ?TradingRepository $repository = null)
    {
        $this->db = $db;
        $this->repository = $repository ?? new TradingRepository($db);
        $this->commonRepository = new \Services\CommonMysqliRepository($db);
    }

    /**
     * @see CashTransactionHandlerInterface::generateUniquePid()
     */
    public function generateUniquePid(int $pid): int
    {
        if (!$this->repository->playerIdExists($pid)) {
            return $pid;
        }
        
        return $this->generateUniquePid($pid + 2);
    }

    /**
     * @see CashTransactionHandlerInterface::calculateContractTotalYears()
     */
    public function calculateContractTotalYears(array $cashYear): int
    {
        if (($cashYear[6] ?? 0) != 0) {
            return 6;
        } elseif (($cashYear[5] ?? 0) != 0) {
            return 5;
        } elseif (($cashYear[4] ?? 0) != 0) {
            return 4;
        } elseif (($cashYear[3] ?? 0) != 0) {
            return 3;
        } elseif (($cashYear[2] ?? 0) != 0) {
            return 2;
        } else {
            return 1;
        }
    }

    /**
     * @see CashTransactionHandlerInterface::createCashTransaction()
     */
    public function createCashTransaction(int $itemId, string $offeringTeamName, string $listeningTeamName, array $cashYear): array
    {
        $offeringTeamId = $this->commonRepository->getTidFromTeamname($offeringTeamName);
        $listeningTeamId = $this->commonRepository->getTidFromTeamname($listeningTeamName);
        
        // Use null coalescing to default missing years to 0
        $cy1 = (int) ($cashYear[1] ?? 0);
        $cy2 = (int) ($cashYear[2] ?? 0);
        $cy3 = (int) ($cashYear[3] ?? 0);
        $cy4 = (int) ($cashYear[4] ?? 0);
        $cy5 = (int) ($cashYear[5] ?? 0);
        $cy6 = (int) ($cashYear[6] ?? 0);

        $contractCurrentYear = 1;
        $contractTotalYears = $this->calculateContractTotalYears($cashYear);

        // Insert positive cash row (for offering team)
        // UUID is generated by database trigger on insert
        $affectedRowsPositive = $this->repository->insertCashPlayerRecord([
            'ordinal' => 100000,
            'pid' => $itemId,
            'name' => "| <B>Cash to $listeningTeamName</B>",
            'tid' => $offeringTeamId,
            'teamname' => $offeringTeamName,
            'exp' => $contractCurrentYear,
            'cy' => $contractCurrentYear,
            'cyt' => $contractTotalYears,
            'cy1' => $cy1,
            'cy2' => $cy2,
            'cy3' => $cy3,
            'cy4' => $cy4,
            'cy5' => $cy5,
            'cy6' => $cy6,
            'retired' => 0
        ]);

        $itemId++;

        // Insert negative cash row (for listening team)
        // UUID is generated by database trigger on insert
        $affectedRowsNegative = $this->repository->insertCashPlayerRecord([
            'ordinal' => 100000,
            'pid' => $itemId,
            'name' => "| <B>Cash from $offeringTeamName</B>",
            'tid' => $listeningTeamId,
            'teamname' => $listeningTeamName,
            'exp' => $contractCurrentYear,
            'cy' => $contractCurrentYear,
            'cyt' => $contractTotalYears,
            'cy1' => -$cy1,
            'cy2' => -$cy2,
            'cy3' => -$cy3,
            'cy4' => -$cy4,
            'cy5' => -$cy5,
            'cy6' => -$cy6,
            'retired' => 0
        ]);

        $success = ($affectedRowsPositive > 0) && ($affectedRowsNegative > 0);
        $tradeLine = "";

        if ($success) {
            $tradeLine = "The $offeringTeamName send $cy1 $cy2 $cy3 $cy4 $cy5 $cy6 in cash to the $listeningTeamName.<br>";
        }

        return [
            'success' => $success,
            'tradeLine' => $tradeLine
        ];
    }

    /**
     * @see CashTransactionHandlerInterface::insertCashTradeData()
     */
    public function insertCashTradeData(int $tradeOfferId, string $offeringTeamName, string $listeningTeamName, array $cashAmounts): bool
    {
        // Use null coalescing to default missing years to 0
        $cy1 = (int) ($cashAmounts[1] ?? 0);
        $cy2 = (int) ($cashAmounts[2] ?? 0);
        $cy3 = (int) ($cashAmounts[3] ?? 0);
        $cy4 = (int) ($cashAmounts[4] ?? 0);
        $cy5 = (int) ($cashAmounts[5] ?? 0);
        $cy6 = (int) ($cashAmounts[6] ?? 0);

        $affectedRows = $this->repository->insertCashTradeOffer(
            $tradeOfferId,
            $offeringTeamName,
            $listeningTeamName,
            $cy1,
            $cy2,
            $cy3,
            $cy4,
            $cy5,
            $cy6
        );

        return $affectedRows > 0;
    }

    /**
     * @see CashTransactionHandlerInterface::hasCashInTrade()
     */
    public function hasCashInTrade(array $cashAmounts): bool
    {
        foreach ($cashAmounts as $amount) {
            if (!empty($amount) && (int)$amount !== 0) {
                return true;
            }
        }
        return false;
    }
}