<?php

declare(strict_types=1);

namespace Trading;

use Trading\Contracts\CashTransactionHandlerInterface;

/**
 * CashTransactionHandler - Handles cash considerations in trades
 *
 * Manages the creation of cash entries in trades including generating unique
 * player IDs for cash transactions and creating the paired positive/negative
 * cash records for trading teams.
 * 
 * @see CashTransactionHandlerInterface
 */
class CashTransactionHandler implements CashTransactionHandlerInterface
{
    protected $db;
    protected \Services\CommonRepository $commonRepository;

    public function __construct($db)
    {
        $this->db = $db;
        $this->commonRepository = new \Services\CommonRepository($db);
    }

    /**
     * @see CashTransactionHandlerInterface::generateUniquePid()
     */
    public function generateUniquePid(int $pid): int
    {
        $queryCheckIfPidExists = "SELECT 1 FROM ibl_plr WHERE pid = $pid";
        $resultCheckIfPidExists = $this->db->sql_query($queryCheckIfPidExists);
        $pidResult = $this->db->sql_result($resultCheckIfPidExists, 0);

        if ($pidResult == NULL) {
            return $pid;
        } else {
            $pid += 2;
            return $this->generateUniquePid($pid);
        }
    }

    /**
     * @see CashTransactionHandlerInterface::calculateContractTotalYears()
     */
    public function calculateContractTotalYears(array $cashYear): int
    {
        if (($cashYear[6] ?? 0) != 0) {
            return 6;
        } elseif (($cashYear[5] ?? 0) != 0) {
            return 5;
        } elseif (($cashYear[4] ?? 0) != 0) {
            return 4;
        } elseif (($cashYear[3] ?? 0) != 0) {
            return 3;
        } elseif (($cashYear[2] ?? 0) != 0) {
            return 2;
        } else {
            return 1;
        }
    }

    /**
     * @see CashTransactionHandlerInterface::createCashTransaction()
     */
    public function createCashTransaction(int $itemId, string $offeringTeamName, string $listeningTeamName, array $cashYear): array
    {
        $offeringTeamId = $this->commonRepository->getTidFromTeamname($offeringTeamName);
        $listeningTeamId = $this->commonRepository->getTidFromTeamname($listeningTeamName);
        
        // Use null coalescing to default missing years to 0
        $cy1 = (int) ($cashYear[1] ?? 0);
        $cy2 = (int) ($cashYear[2] ?? 0);
        $cy3 = (int) ($cashYear[3] ?? 0);
        $cy4 = (int) ($cashYear[4] ?? 0);
        $cy5 = (int) ($cashYear[5] ?? 0);
        $cy6 = (int) ($cashYear[6] ?? 0);

        $contractCurrentYear = 1;
        $contractTotalYears = $this->calculateContractTotalYears($cashYear);

        // Insert positive cash row (for offering team)
        // UUID is generated by database trigger on insert
        $queryInsertPositiveCashRow = "INSERT INTO `ibl_plr` 
            (`ordinal`, 
            `pid`, 
            `name`, 
            `tid`, 
            `teamname`, 
            `exp`, 
            `cy`, 
            `cyt`, 
            `cy1`, 
            `cy2`, 
            `cy3`, 
            `cy4`, 
            `cy5`, 
            `cy6`) 
        VALUES
            ('100000',
            '$itemId',
            '| <B>Cash to $listeningTeamName</B>',
            '$offeringTeamId',
            '$offeringTeamName',
            '$contractCurrentYear',
            '$contractCurrentYear',
            '$contractTotalYears',
            '$cy1',
            '$cy2',
            '$cy3',
            '$cy4',
            '$cy5',
            '$cy6')";

        $resultInsertPositiveCashRow = $this->db->sql_query($queryInsertPositiveCashRow);

        $itemId++;

        // Insert negative cash row (for listening team)
        // UUID is generated by database trigger on insert
        $queryInsertNegativeCashRow = "INSERT INTO `ibl_plr` 
            (`ordinal`,
            `pid`,
            `name`,
            `tid`,
            `teamname`,
            `exp`,
            `cy`,
            `cyt`,
            `cy1`,
            `cy2`,
            `cy3`,
            `cy4`,
            `cy5`,
            `cy6`)
        VALUES
            ('100000',
            '$itemId',
            '| <B>Cash from $offeringTeamName</B>',
            '$listeningTeamId',
            '$listeningTeamName',
            '$contractCurrentYear',
            '$contractCurrentYear',
            '$contractTotalYears',
            '-$cy1',
            '-$cy2',
            '-$cy3',
            '-$cy4',
            '-$cy5',
            '-$cy6')";

        $resultInsertNegativeCashRow = $this->db->sql_query($queryInsertNegativeCashRow);

        $success = $resultInsertPositiveCashRow && $resultInsertNegativeCashRow;
        $tradeLine = "";

        if ($success) {
            $tradeLine = "The $offeringTeamName send $cy1 $cy2 $cy3 $cy4 $cy5 $cy6 in cash to the $listeningTeamName.<br>";
        }

        return [
            'success' => $success,
            'tradeLine' => $tradeLine
        ];
    }

    /**
     * @see CashTransactionHandlerInterface::insertCashTradeData()
     */
    public function insertCashTradeData(int $tradeOfferId, string $offeringTeamName, string $listeningTeamName, array $cashAmounts): bool
    {
        // Use null coalescing to default missing years to 0
        $cy1 = (int) ($cashAmounts[1] ?? 0);
        $cy2 = (int) ($cashAmounts[2] ?? 0);
        $cy3 = (int) ($cashAmounts[3] ?? 0);
        $cy4 = (int) ($cashAmounts[4] ?? 0);
        $cy5 = (int) ($cashAmounts[5] ?? 0);
        $cy6 = (int) ($cashAmounts[6] ?? 0);

        $query = "INSERT INTO ibl_trade_cash
          ( `tradeOfferID`,
            `sendingTeam`,
            `receivingTeam`,
            `cy1`,
            `cy2`,
            `cy3`,
            `cy4`,
            `cy5`,
            `cy6` )
        VALUES    ( '$tradeOfferId',
            '$offeringTeamName',
            '$listeningTeamName',
            '$cy1',
            '$cy2',
            '$cy3',
            '$cy4',
            '$cy5',
            '$cy6' )";

        return (bool)$this->db->sql_query($query);
    }

    /**
     * @see CashTransactionHandlerInterface::hasCashInTrade()
     */
    public function hasCashInTrade(array $cashAmounts): bool
    {
        foreach ($cashAmounts as $amount) {
            if (!empty($amount) && (int)$amount !== 0) {
                return true;
            }
        }
        return false;
    }
}