<?php

require_once __DIR__ . '/Contracts/Trading_CashTransactionHandlerInterface.php';

/**
 * @see Trading_CashTransactionHandlerInterface
 */
class Trading_CashTransactionHandler implements Trading_CashTransactionHandlerInterface
{
    protected $db;
    protected $commonRepository;

    public function __construct($db)
    {
        $this->db = $db;
        $this->commonRepository = new \Services\CommonRepository($db);
    }

    /**
     * @see Trading_CashTransactionHandlerInterface::generateUniquePid()
     */
    public function generateUniquePid($pid)
    {
        $queryCheckIfPidExists = "SELECT 1 FROM ibl_plr WHERE pid = $pid";
        $resultCheckIfPidExists = $this->db->sql_query($queryCheckIfPidExists);
        $pidResult = $this->db->sql_result($resultCheckIfPidExists, 0);

        if ($pidResult == NULL) {
            return $pid;
        } else {
            $pid += 2;
            return $this->generateUniquePid($pid);
        }
    }

    /**
     * @see Trading_CashTransactionHandlerInterface::calculateContractTotalYears()
     */
    public function calculateContractTotalYears($cashYear)
    {
        if ($cashYear[6] != 0) {
            return 6;
        } elseif ($cashYear[5] != 0) {
            return 5;
        } elseif ($cashYear[4] != 0) {
            return 4;
        } elseif ($cashYear[3] != 0) {
            return 3;
        } elseif ($cashYear[2] != 0) {
            return 2;
        } else {
            return 1;
        }
    }

    /**
     * @see Trading_CashTransactionHandlerInterface::createCashTransaction()
     */
    public function createCashTransaction($itemId, $offeringTeamName, $listeningTeamName, $cashYear)
    {
        $offeringTeamId = $this->commonRepository->getTidFromTeamname($offeringTeamName);
        $listeningTeamId = $this->commonRepository->getTidFromTeamname($listeningTeamName);
        
        // Use null coalescing to default missing years to 0
        $cy1 = $cashYear[1] ?? 0;
        $cy2 = $cashYear[2] ?? 0;
        $cy3 = $cashYear[3] ?? 0;
        $cy4 = $cashYear[4] ?? 0;
        $cy5 = $cashYear[5] ?? 0;
        $cy6 = $cashYear[6] ?? 0;

        $contractCurrentYear = 1;
        $contractTotalYears = $this->calculateContractTotalYears($cashYear);

        // Insert positive cash row (for offering team)
        // UUID is generated by database trigger on insert
        $queryInsertPositiveCashRow = "INSERT INTO `ibl_plr` 
            (`ordinal`, 
            `pid`, 
            `name`, 
            `tid`, 
            `teamname`, 
            `exp`, 
            `cy`, 
            `cyt`, 
            `cy1`, 
            `cy2`, 
            `cy3`, 
            `cy4`, 
            `cy5`, 
            `cy6`,
            `retired`) 
        VALUES
            ('100000',
            '$itemId',
            '| <B>Cash to $listeningTeamName</B>',
            '$offeringTeamId',
            '$offeringTeamName',
            '$contractCurrentYear',
            '$contractCurrentYear',
            '$contractTotalYears',
            '$cy1',
            '$cy2',
            '$cy3',
            '$cy4',
            '$cy5',
            '$cy6',
            '0')";

        $resultInsertPositiveCashRow = $this->db->sql_query($queryInsertPositiveCashRow);

        $itemId++;

        // Insert negative cash row (for listening team)
        // UUID is generated by database trigger on insert
        $queryInsertNegativeCashRow = "INSERT INTO `ibl_plr` 
            (`ordinal`,
            `pid`,
            `name`,
            `tid`,
            `teamname`,
            `exp`,
            `cy`,
            `cyt`,
            `cy1`,
            `cy2`,
            `cy3`,
            `cy4`,
            `cy5`,
            `cy6`,
            `retired`)
        VALUES
            ('100000',
            '$itemId',
            '| <B>Cash from $offeringTeamName</B>',
            '$listeningTeamId',
            '$listeningTeamName',
            '$contractCurrentYear',
            '$contractCurrentYear',
            '$contractTotalYears',
            '-$cy1',
            '-$cy2',
            '-$cy3',
            '-$cy4',
            '-$cy5',
            '-$cy6',
            '0')";

        $resultInsertNegativeCashRow = $this->db->sql_query($queryInsertNegativeCashRow);

        $success = $resultInsertPositiveCashRow && $resultInsertNegativeCashRow;
        $tradeLine = "";

        if ($success) {
            $tradeLine = "The $offeringTeamName send $cy1 $cy2 $cy3 $cy4 $cy5 $cy6 in cash to the $listeningTeamName.<br>";
        }

        return [
            'success' => $success,
            'tradeLine' => $tradeLine
        ];
    }

    /**
     * @see Trading_CashTransactionHandlerInterface::insertCashTradeData()
     */
    public function insertCashTradeData($tradeOfferId, $offeringTeamName, $listeningTeamName, $cashAmounts)
    {
        // Use null coalescing to default missing years to 0
        $cy1 = $cashAmounts[1] ?? 0;
        $cy2 = $cashAmounts[2] ?? 0;
        $cy3 = $cashAmounts[3] ?? 0;
        $cy4 = $cashAmounts[4] ?? 0;
        $cy5 = $cashAmounts[5] ?? 0;
        $cy6 = $cashAmounts[6] ?? 0;

        $query = "INSERT INTO ibl_trade_cash
          ( `tradeOfferID`,
            `sendingTeam`,
            `receivingTeam`,
            `cy1`,
            `cy2`,
            `cy3`,
            `cy4`,
            `cy5`,
            `cy6` )
        VALUES    ( '$tradeOfferId',
            '$offeringTeamName',
            '$listeningTeamName',
            '$cy1',
            '$cy2',
            '$cy3',
            '$cy4',
            '$cy5',
            '$cy6' )";

        return (bool)$this->db->sql_query($query);
    }

    /**
     * @see Trading_CashTransactionHandlerInterface::hasCashInTrade()
     */
    public function hasCashInTrade($cashAmounts)
    {
        foreach ($cashAmounts as $amount) {
            if (!empty($amount) && (int)$amount !== 0) {
                return true;
            }
        }
        return false;
    }
}