<?php

declare(strict_types=1);

namespace Trading\Contracts;

/**
 * CashTransactionHandlerInterface - Cash transaction management for trades
 *
 * Handles creation and validation of cash transactions within trades,
 * including database insertions for both positive (sending) and negative
 * (receiving) cash entries.
 * 
 * @package Trading\Contracts
 */
interface CashTransactionHandlerInterface
{
    /**
     * Generate a unique PID that doesn't exist in the database
     *
     * Recursively checks for an available PID starting from the given value,
     * incrementing by 2 until finding one that doesn't exist in ibl_plr table.
     *
     * @param int $pid Starting PID to check
     * @return int Available PID that can be used for a new record
     *
     * IMPORTANT BEHAVIORS:
     *  - Recursively searches for available PID
     *  - Increments by 2 on each iteration (preserves odd/even pattern)
     *  - Returns the first PID that has no matching record in ibl_plr
     */
    public function generateUniquePid(int $pid): int;

    /**
     * Calculate contract total years based on cash year data
     *
     * Determines how many years a cash consideration spans by checking
     * which years have non-zero amounts, starting from year 6 down to year 1.
     *
     * @param array<int, int> $cashYear Array of cash amounts indexed by year (1-6)
     * @return int Total contract years (1-6)
     *
     * IMPORTANT BEHAVIORS:
     *  - Checks years 6 down to 1
     *  - Returns the highest year number with a non-zero value
     *  - Returns 1 if only year 1 has a value (minimum 1 year)
     */
    public function calculateContractTotalYears(array $cashYear): int;

    /**
     * Create cash transaction entries in the database
     *
     * Inserts two records into ibl_plr table:
     * 1. Positive cash row for the offering team (shows cash outgoing)
     * 2. Negative cash row for the listening team (shows cash incoming)
     *
     * @param int $itemId Unique item ID for the transaction (will be incremented for second record)
     * @param string $offeringTeamName Name of team sending the cash
     * @param string $listeningTeamName Name of team receiving the cash
     * @param array<int, int> $cashYear Cash amounts indexed by year (1-6)
     * @return array{success: bool, tradeLine: string} Result:
     *         - 'success': bool - Whether both inserts succeeded
     *         - 'tradeLine': string - Description text for the trade (empty on failure)
     *
     * IMPORTANT BEHAVIORS:
     *  - Creates player-like records with ordinal 100000 (cash marker)
     *  - Names formatted as "| <B>Cash to {team}</B>" and "| <B>Cash from {team}</B>"
     *  - UUIDs generated by database trigger on insert
     *  - Negative amounts stored for receiving team entries
     */
    public function createCashTransaction(int $itemId, string $offeringTeamName, string $listeningTeamName, array $cashYear): array;

    /**
     * Insert cash trade data into ibl_trade_cash table
     *
     * Records the cash amounts by year for a trade offer, used during
     * trade processing to retrieve the original cash terms.
     *
     * @param int $tradeOfferId Trade offer ID to associate with
     * @param string $offeringTeamName Name of team sending the cash
     * @param string $listeningTeamName Name of team receiving the cash
     * @param array<int, int> $cashAmounts Cash amounts indexed by year (1-6), missing years default to 0
     * @return bool True on successful insert
     *
     * IMPORTANT BEHAVIORS:
     *  - Initializes any missing year values to 0
     *  - Stores amounts for years 1-6 (cy1 through cy6)
     */
    public function insertCashTradeData(int $tradeOfferId, string $offeringTeamName, string $listeningTeamName, array $cashAmounts): bool;

    /**
     * Check if any cash is being sent in the trade
     *
     * @param array<int, int> $cashAmounts Cash amounts indexed by year (1-6)
     * @return bool True if any year has a non-zero amount
     *
     * IMPORTANT BEHAVIORS:
     *  - Checks all 6 years for non-zero values
     *  - Treats null/missing values as 0
     *  - Returns true if ANY year has cash, false otherwise
     */
    public function hasCashInTrade(array $cashAmounts): bool;
}
