#!/bin/sh
# Ensure vendor/ is populated before Apache starts.
# On first run (named volume empty), runs composer install automatically.
# On subsequent runs, detects autoload.php and skips install immediately.

APP_DIR="/var/www/html/ibl5"
VENDOR="$APP_DIR/vendor/autoload.php"
LOGS_DIR="$APP_DIR/logs"

# Ensure logs/ directory exists and is writable by www-data (Apache user).
mkdir -p "$LOGS_DIR"
chown www-data:www-data "$LOGS_DIR"

# Detect broken symlink (shouldn't happen with named volume, but guard anyway)
if [ -L "$APP_DIR/vendor" ] && [ ! -e "$APP_DIR/vendor" ]; then
    echo "ERROR: $APP_DIR/vendor is a broken symlink."
    exit 1
fi

# Run composer install if vendor is missing or incomplete
if [ ! -f "$VENDOR" ]; then
    echo "vendor/autoload.php not found — running composer install..."
    cd "$APP_DIR" && composer install --no-interaction --no-progress --prefer-dist --no-dev
    echo "composer install complete."
fi

# Auto-create mail config for Docker (Mailpit SMTP) if none exists.
# Only creates — never overwrites an existing config.
MAIL_CONFIG="$APP_DIR/config/mail.config.php"
if [ ! -f "$MAIL_CONFIG" ]; then
    cat > "$MAIL_CONFIG" << 'MAILCONF'
<?php
// Auto-generated by Docker entrypoint — routes mail to Mailpit.
// View captured emails at http://localhost:8025
// Override by editing this file; it won't be regenerated.
return [
    'transport' => 'smtp',
    'smtp' => [
        'host' => 'ibl5-mailpit',
        'port' => 1025,
        'encryption' => '',
        'username' => '',
        'password' => '',
    ],
    'default_from_email' => 'noreply@iblhoops.net',
    'default_from_name' => 'IBL',
];
MAILCONF
    echo "Created mail.config.php (Mailpit SMTP)."
fi

exec "$@"
