#!/bin/sh
# Pre-flight setup before Apache starts.
# Handles DB initialization, migrations, schema validation, and cache warming
# so that `docker compose up -d` is the only command needed.

set -e

APP_DIR="/var/www/html/ibl5"
LOGS_DIR="$APP_DIR/logs"
DB_HOST="${DB_HOST:-mariadb}"
DB_NAME="iblhoops_ibl5"

# Wrapper to suppress MariaDB "password on command line" warning.
# --skip-ssl: Docker-internal connections don't use TLS.
db_exec() {
    mariadb -h "$DB_HOST" --skip-ssl -u root -proot "$DB_NAME" "$@" 2>&1 | grep -v '\[Warning\].*password' || true
}

# PHP CLI scripts (migrate, validate-schema) include config.php which reads
# $_SERVER['SERVER_NAME']. Set it here so CLI context has it.
export SERVER_NAME=localhost

# ── Phase 0: Worktree mount guard ──────────────────────────────────────────
# Worktrees symlink vendor/ to the main repo — that symlink is unresolvable
# inside a container. If vendor is a dangling symlink, this container was
# launched via `docker compose up` from a worktree directory instead of
# using `bin/wt-up`. Abort with a clear message.
if [ -L "$APP_DIR/vendor" ] && [ ! -e "$APP_DIR/vendor" ]; then
    echo ""
    echo "============================================================"
    echo "  FATAL: Dangling vendor symlink detected."
    echo ""
    echo "  This container was started from a worktree directory using"
    echo "  the main docker-compose.yml. Worktree Docker environments"
    echo "  must be started with bin/wt-up <name>, not docker compose."
    echo ""
    echo "  To fix:"
    echo "    1. Stop this container"
    echo "    2. Run: docker compose up -d   (from the main repo root)"
    echo "       OR:  bin/wt-up <worktree-name>"
    echo "============================================================"
    echo ""
    exit 1
fi

# ── Phase 1: Filesystem setup ───────────────────────────────────────────────
mkdir -p "$LOGS_DIR"
chown www-data:www-data "$LOGS_DIR"

# Auto-create mail config for Docker (Mailpit SMTP) if none exists.
MAIL_CONFIG="$APP_DIR/config/mail.config.php"
if [ ! -f "$MAIL_CONFIG" ]; then
    cat > "$MAIL_CONFIG" << 'MAILCONF'
<?php
// Auto-generated by Docker entrypoint — routes mail to Mailpit.
// View captured emails at http://localhost:8025
// Override by editing this file; it won't be regenerated.
return [
    'transport' => 'smtp',
    'smtp' => [
        'host' => 'ibl5-mailpit',
        'port' => 1025,
        'encryption' => '',
        'username' => '',
        'password' => '',
    ],
    'default_from_email' => 'noreply@iblhoops.net',
    'default_from_name' => 'IBL',
];
MAILCONF
    echo "[entrypoint] Created mail.config.php (Mailpit SMTP)."
fi

# ── Phase 2: DB initialization (only on empty database) ─────────────────────
TABLE_COUNT=$(db_exec -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME';" | tr -d '[:space:]')

if ! echo "$TABLE_COUNT" | grep -qE '^[0-9]+$'; then
    echo "[entrypoint] ERROR: Could not query table count (got: $TABLE_COUNT). Check DB connection."
    echo "[entrypoint] Continuing without DB initialization..."
    TABLE_COUNT="-1"
fi

if [ "$TABLE_COUNT" = "0" ] && [ "${SKIP_PROD_SEED:-}" != "1" ]; then
    PROD_SEED="$APP_DIR/fixtures/prod-seed.sql"
    if [ -f "$PROD_SEED" ]; then
        echo "[entrypoint] Empty database detected. Importing prod-seed.sql..."
        echo "[entrypoint] This may take 1-2 minutes for the 87MB dump."
        # The prod-seed is a two-part dump (schema then data). The schema
        # section's footer restores FOREIGN_KEY_CHECKS=1 before data inserts
        # begin, causing FK violations on tables with cross-references.
        # Fix: wrap the entire import in FOREIGN_KEY_CHECKS=0.
        # --force: continue past non-fatal errors (e.g. ERROR 1906 for
        # generated-column values that MariaDB safely ignores).
        # Also strip DEFINER clauses — prod exports contain DEFINER=user@host
        # that don't exist in Docker MariaDB, causing ERROR 1449 on import.
        { echo "SET FOREIGN_KEY_CHECKS=0;"; sed 's/ DEFINER=[^ ]* / /g' "$PROD_SEED"; echo "SET FOREIGN_KEY_CHECKS=1;"; } \
            | mariadb --force -h "$DB_HOST" --skip-ssl -u root -proot "$DB_NAME" 2>&1 \
            | grep -v '\[Warning\].*password' \
            | grep -i 'ERROR' > /tmp/import-errors.log || true
        if [ -s /tmp/import-errors.log ]; then
            if grep -v 'ERROR 1906' /tmp/import-errors.log | grep -qi 'ERROR'; then
                echo "[entrypoint] ERROR: Prod-seed import had fatal errors:"
                grep -v 'ERROR 1906' /tmp/import-errors.log
                exit 1
            fi
            WARN_COUNT=$(wc -l < /tmp/import-errors.log | tr -d '[:space:]')
            echo "[entrypoint] Import completed with $WARN_COUNT generated-column warnings (harmless)."
        fi
        rm -f /tmp/import-errors.log
        echo "[entrypoint] Prod-seed import complete."
    else
        echo "[entrypoint] WARNING: Empty database and no prod-seed.sql found."
        echo "[entrypoint] The app will not work until data is imported."
        echo "[entrypoint] Provide ibl5/fixtures/prod-seed.sql or run migrations manually."
    fi
else
    echo "[entrypoint] Database has $TABLE_COUNT tables — skipping prod-seed import."
fi

# ── Phase 3: Migrations (always, idempotent) ────────────────────────────────
echo "[entrypoint] Running pending migrations..."
php "$APP_DIR/bin/migrate" 2>&1 || echo "[entrypoint] WARNING: Migration runner failed (non-fatal)."

# ── Phase 4: Schema validation (warn-only) ──────────────────────────────────
echo "[entrypoint] Validating schema..."
php "$APP_DIR/bin/validate-schema" 2>&1 || echo "[entrypoint] WARNING: Schema validation failed. Check migrations."

# ── Phase 5: Vendor check ───────────────────────────────────────────────────
if [ ! -f "$APP_DIR/vendor/autoload.php" ]; then
    echo "[entrypoint] WARNING: vendor/autoload.php not found."
    echo "[entrypoint] Run 'composer install' on the host to install dependencies."
fi

# ── Phase 6: Purge stale page cache and warm caches ─────────────────────────
if [ -f "$APP_DIR/vendor/autoload.php" ]; then
    echo "[entrypoint] Purging page cache..."
    php -r "require '$APP_DIR/vendor/autoload.php'; Cache\PageCache::purge();" 2>/dev/null || true
    echo "[entrypoint] Warming caches in background..."
    (php "$APP_DIR/bin/warm-cache" >> "$LOGS_DIR/warm-cache.log" 2>&1) &
fi

# ── Phase 7: Start Apache ───────────────────────────────────────────────────
echo "[entrypoint] Starting Apache."
exec "$@"
