#!/bin/sh
# Pre-flight setup before Apache starts.
# vendor/ is bind-mounted read-only from the host — no composer install needed.

APP_DIR="/var/www/html/ibl5"
LOGS_DIR="$APP_DIR/logs"

# Ensure logs/ directory exists and is writable by www-data (Apache user).
mkdir -p "$LOGS_DIR"
chown www-data:www-data "$LOGS_DIR"

# Auto-create mail config for Docker (Mailpit SMTP) if none exists.
# Only creates — never overwrites an existing config.
MAIL_CONFIG="$APP_DIR/config/mail.config.php"
if [ ! -f "$MAIL_CONFIG" ]; then
    cat > "$MAIL_CONFIG" << 'MAILCONF'
<?php
// Auto-generated by Docker entrypoint — routes mail to Mailpit.
// View captured emails at http://localhost:8025
// Override by editing this file; it won't be regenerated.
return [
    'transport' => 'smtp',
    'smtp' => [
        'host' => 'ibl5-mailpit',
        'port' => 1025,
        'encryption' => '',
        'username' => '',
        'password' => '',
    ],
    'default_from_email' => 'noreply@iblhoops.net',
    'default_from_name' => 'IBL',
];
MAILCONF
    echo "Created mail.config.php (Mailpit SMTP)."
fi

exec "$@"
