<?php

declare(strict_types=1);

namespace JsbParser;

use JsbParser\Contracts\LeadersHtmParserInterface;

/**
 * Parser for JSB Leaders.htm files.
 *
 * Extracts individual awards, stat leaders, and team selections from the HTML
 * generated by the Jump Shot Basketball simulation engine.
 *
 * @see LeadersHtmParserInterface
 */
class LeadersHtmParser implements LeadersHtmParserInterface
{
    /** @var array<string, string> Maps Leaders.htm section headers to DB award names */
    private const INDIVIDUAL_HEADER_MAP = [
        'most valuable player' => 'Most Valuable Player',
        'defensive player' => 'Defensive Player of the Year',
        'rookie of the year' => 'Rookie of the Year',
        '6th man award' => '6th Man Award',
    ];

    /** @var array<string, string> Maps Leaders.htm stat leader headers to DB award names */
    private const STAT_LEADER_HEADER_MAP = [
        'scoring leader' => 'Scoring Leader',
        'rebound leader' => 'Rebounding Leader',
        'assists leader' => 'Assists Leader',
        'steals leader' => 'Steals Leader',
        'blocks leader' => 'Blocks Leader',
    ];

    /** @var array<string, string> Maps Leaders.htm team headers to DB award names */
    private const TEAM_HEADER_MAP = [
        'all league 1st' => 'All-League First Team',
        'all league 2nd' => 'All-League Second Team',
        'all league 3rd' => 'All-League Third Team',
        'all defense 1st' => 'All-Defensive Team (1st)',
        'all defense 2nd' => 'All-Defensive Team (2nd)',
        'all defense 3rd' => 'All-Defensive Team (3rd)',
        'all rookie 1st' => 'All-Rookie Team (1st)',
        'all rookie 2nd' => 'All-Rookie Team (2nd)',
        'all rookie 3rd' => 'All-Rookie Team (3rd)',
    ];

    /**
     * @see LeadersHtmParserInterface::parseFile()
     */
    public static function parseFile(string $filePath): array
    {
        if (!file_exists($filePath)) {
            throw new \RuntimeException("Leaders.htm file not found: {$filePath}");
        }

        $content = file_get_contents($filePath);
        if ($content === false) {
            throw new \RuntimeException("Failed to read Leaders.htm file: {$filePath}");
        }

        $result = [
            'individual' => [],
            'stat_leaders' => [],
            'teams' => [],
        ];

        // Split content into sections by <tr><th> header rows
        $sections = self::splitIntoSections($content);

        foreach ($sections as $section) {
            $headerText = $section['header'];
            $rows = $section['rows'];

            // Check if this is a team section (9-column layout)
            if (self::isTeamSection($headerText)) {
                self::parseTeamSection($headerText, $rows, $result);
                continue;
            }

            // Check if this is a stat leader section
            $statLeaderName = self::matchStatLeaderHeader($headerText);
            if ($statLeaderName !== null) {
                $result['stat_leaders'][$statLeaderName] = self::parseStatLeaderRows($rows);
                continue;
            }

            // Check if this is an individual award section
            $individualName = self::matchIndividualHeader($headerText);
            if ($individualName !== null) {
                $result['individual'][$individualName] = self::parseIndividualRows($rows);
            }
        }

        return $result;
    }

    /**
     * Split HTML content into sections based on <tr><th> header rows.
     *
     * @return list<array{header: string, rows: list<string>}>
     */
    private static function splitIntoSections(string $content): array
    {
        $sections = [];

        // Find all table rows
        if (preg_match_all('/<tr>(.*?)<\/tr>/si', $content, $matches) === 0 || $matches === []) {
            return [];
        }

        $currentHeader = null;
        /** @var list<string> $currentRows */
        $currentRows = [];

        foreach ($matches[1] as $rowContent) {
            // Check if this row contains <th> elements (header row)
            if (preg_match('/<th/i', $rowContent) === 1) {
                // If we have a pending section, save it
                if ($currentHeader !== null && $currentRows !== []) {
                    $sections[] = ['header' => $currentHeader, 'rows' => $currentRows];
                    $currentRows = [];
                }

                // Extract header text (skip "po", "player", "team" sub-headers)
                $headerText = self::extractHeaderText($rowContent);
                if ($headerText !== '' && strtolower($headerText) !== 'po') {
                    $currentHeader = $headerText;
                    $currentRows = [];
                }
                continue;
            }

            // Data row — add to current section
            if ($currentHeader !== null && preg_match('/<td/i', $rowContent) === 1) {
                $currentRows[] = $rowContent;
            }
        }

        // Save final section
        if ($currentHeader !== null && $currentRows !== []) {
            $sections[] = ['header' => $currentHeader, 'rows' => $currentRows];
        }

        return $sections;
    }

    /**
     * Extract meaningful header text from a <th> row, ignoring layout-only headers.
     */
    private static function extractHeaderText(string $rowContent): string
    {
        if (preg_match_all('/<th[^>]*>(.*?)<\/th>/si', $rowContent, $matches) === 0 || $matches === []) {
            return '';
        }

        $texts = [];
        foreach ($matches[1] as $text) {
            $cleaned = trim(strip_tags($text));
            if ($cleaned !== '' && strtolower($cleaned) !== 'po' && strtolower($cleaned) !== 'player' && strtolower($cleaned) !== 'team') {
                $texts[] = $cleaned;
            }
        }

        return implode('|', $texts);
    }

    /**
     * Check if a header represents a team section (All League, All Defense, All Rookie).
     */
    private static function isTeamSection(string $headerText): bool
    {
        $lower = strtolower($headerText);
        return str_contains($lower, 'all league') || str_contains($lower, 'all defense') || str_contains($lower, 'all rookie');
    }

    /**
     * Match a header to a stat leader DB name.
     */
    private static function matchStatLeaderHeader(string $headerText): ?string
    {
        $lower = strtolower($headerText);
        foreach (self::STAT_LEADER_HEADER_MAP as $pattern => $dbName) {
            if (str_contains($lower, $pattern)) {
                return $dbName;
            }
        }
        return null;
    }

    /**
     * Match a header to an individual award DB name.
     */
    private static function matchIndividualHeader(string $headerText): ?string
    {
        $lower = strtolower($headerText);
        foreach (self::INDIVIDUAL_HEADER_MAP as $pattern => $dbName) {
            if (str_contains($lower, $pattern)) {
                return $dbName;
            }
        }
        return null;
    }

    /**
     * Parse individual award rows (3-column: position, name, team).
     *
     * @param list<string> $rows Raw HTML row contents
     * @return list<string> Player names in order
     */
    private static function parseIndividualRows(array $rows): array
    {
        $names = [];
        foreach ($rows as $row) {
            $cells = self::extractCellValues($row);
            // Column 1 (index 1) is the player name
            if (count($cells) >= 2 && $cells[1] !== '') {
                $names[] = $cells[1];
            }
        }
        return $names;
    }

    /**
     * Parse stat leader rows (4-column: position, name, team, stat).
     *
     * @param list<string> $rows Raw HTML row contents
     * @return list<array{name: string, stat: string}>
     */
    private static function parseStatLeaderRows(array $rows): array
    {
        $leaders = [];
        foreach ($rows as $row) {
            $cells = self::extractCellValues($row);
            // Column 1 = name, Column 3 = stat value
            if (count($cells) >= 4 && $cells[1] !== '') {
                $leaders[] = [
                    'name' => $cells[1],
                    'stat' => $cells[3],
                ];
            }
        }
        return $leaders;
    }

    /**
     * Parse team section rows (9-column: 3 teams side-by-side).
     *
     * @param list<string> $rows Raw HTML row contents
     * @param array{individual: array<string, list<string>>, stat_leaders: array<string, list<array{name: string, stat: string}>>, teams: array<string, list<string>>} $result
     */
    private static function parseTeamSection(string $headerText, array $rows, array &$result): void
    {
        // Header contains pipe-separated team labels like "All League 1st|All League 2nd|All League 3rd"
        $headers = explode('|', $headerText);
        $teamNames = [];
        foreach ($headers as $header) {
            $lower = strtolower(trim($header));
            if (isset(self::TEAM_HEADER_MAP[$lower])) {
                $teamNames[] = self::TEAM_HEADER_MAP[$lower];
            }
        }

        if (count($teamNames) !== 3) {
            return;
        }

        // Initialize team lists
        $team1 = [];
        $team2 = [];
        $team3 = [];

        foreach ($rows as $row) {
            $cells = self::extractCellValues($row);
            // 9 columns: pos1, name1, team1, pos2, name2, team2, pos3, name3, team3
            if (count($cells) >= 9) {
                if ($cells[1] !== '') {
                    $team1[] = $cells[1];
                }
                if ($cells[4] !== '') {
                    $team2[] = $cells[4];
                }
                if ($cells[7] !== '') {
                    $team3[] = $cells[7];
                }
            }
        }

        $result['teams'][$teamNames[0]] = $team1;
        $result['teams'][$teamNames[1]] = $team2;
        $result['teams'][$teamNames[2]] = $team3;
    }

    /**
     * Extract cell values from a table row's HTML.
     *
     * @return list<string> Cell text values
     */
    private static function extractCellValues(string $rowHtml): array
    {
        if (preg_match_all('/<td[^>]*>(.*?)<\/td>/si', $rowHtml, $matches) === 0 || $matches === []) {
            return [];
        }

        $values = [];
        foreach ($matches[1] as $cellHtml) {
            $values[] = trim(strip_tags($cellHtml));
        }

        return $values;
    }
}
