"""Guard for the Phase 7 CI-fix rerun probe, and the once-per-head baseline re-fire.

A PR labelled `update-baselines` has its e2e baselines regenerated by a workflow job that
removes the label whenever the regen step ran, even when it failed. So a label that is still
on the PR while no e2e run is active means no regen reached its removal step. Rerunning the
failed jobs then burns CI on a state the label owns. This module decides when the probe must
stand down, and when a cancelled or failed regen deserves one more try.

Pure functions over the gh adapter (`pr_has_label_fresh`, `e2e_runs_for_sha`,
`pr_comments_text`, `post_review_summary`, `pr_label_remove`, `pr_label_add_checked`).
Every read fails closed: an error skips the probe and never fires a mutation.
"""
from __future__ import annotations

LABEL = "update-baselines"
ACTIVE = {"queued", "in_progress", "waiting", "requested", "pending"}
REGEN_INCOMPLETE = {"cancelled", "failure", "timed_out", "startup_failure"}

# (pr, sha) pairs this process already re-fired. The hidden PR comment is the durable record;
# this set only stops a second call in the same process from re-reading it.
_REFIRED: set[tuple[int, str]] = set()


def marker(sha: str) -> str:
    return f"<!-- baseline-refire:{sha} -->"


def probe_decision(gh, pr: int, sha: str) -> tuple[bool, str]:
    """(allow, reason). Allow the rerun probe only with no label and no active e2e run."""
    try:
        has_label = gh.pr_has_label_fresh(pr, LABEL)
    except Exception:  # noqa: BLE001 - any read failure must skip the probe
        return False, "label-read-error"
    if has_label:
        return False, "update-baselines-label"
    try:
        runs = gh.e2e_runs_for_sha(sha)
    except Exception:  # noqa: BLE001
        return False, "e2e-read-error"
    if any(r.get("status") in ACTIVE for r in runs):
        return False, "e2e-run-active"
    return True, "clear"


def _ok(fn, *args) -> bool:
    try:
        return bool(fn(*args))
    except Exception:  # noqa: BLE001
        return False


def _comment(gh, pr: int, title: str, body: str) -> bool:
    """post_review_summary returns None and raises on failure."""
    try:
        gh.post_review_summary(pr, title, body)
        return True
    except Exception:  # noqa: BLE001
        return False


def maybe_refire(gh, pr: int, sha: str, log) -> str:
    """Remove and re-add the label once per head when the regen was cancelled or failed.

    Never adds the label to a PR that lacks it. Returns one outcome word, also logged.
    """
    def done(word: str) -> str:
        log(f"phase7 baseline re-fire: {word} sha={str(sha)[:8]}")
        return word

    if (pr, sha) in _REFIRED:
        return done("already-this-process")
    try:
        has_label = gh.pr_has_label_fresh(pr, LABEL)
        if not has_label:
            return done("skip-no-label")
        runs = gh.e2e_runs_for_sha(sha)
    except Exception:  # noqa: BLE001
        return done("skip-read-error")
    if any(r.get("status") in ACTIVE for r in runs):
        return done("skip-run-active")
    if not runs:
        return done("skip-regen-not-incomplete")
    newest = max(runs, key=lambda r: r.get("createdAt") or "")
    if newest.get("conclusion") not in REGEN_INCOMPLETE:
        return done("skip-regen-not-incomplete")
    try:
        comments = gh.pr_comments_text(pr)
    except Exception:  # noqa: BLE001
        return done("skip-read-error")
    if marker(sha) in comments:
        return done("skip-marker")

    # The marker comment goes first: a crash after it still blocks a second re-fire for this head.
    _REFIRED.add((pr, sha))
    body = (f"The `{LABEL}` regen did not finish for `{str(sha)[:8]}` (newest e2e run "
            f"{newest.get('databaseId')}: {newest.get('conclusion')}). Removing and re-adding "
            f"the label once to fire it again.\n\n{marker(sha)}")
    if not _comment(gh, pr, "Baseline regen re-fired", body):
        return done("comment-failed")
    if not _ok(gh.pr_label_remove, pr, LABEL):
        return done("remove-failed")
    if not _ok(gh.pr_label_add_checked, pr, LABEL) and not _ok(gh.pr_label_add_checked, pr, LABEL):
        _comment(gh, pr, "update-baselines label lost",
                 f"The `{LABEL}` label was removed to re-fire the baseline regen, and re-adding "
                 f"it failed twice. Add it back by hand: `gh pr edit {pr} --add-label {LABEL}`.")
        return done("readd-failed")
    return done("refired")
