<?php

declare(strict_types=1);

use Migration\SchemaAssertion;

/**
 * Schema assertions: critical columns that must exist in the database.
 *
 * Convention: When writing a migration that renames or drops a column that
 * PHP code depends on, add a SchemaAssertion here for the destination column.
 * The post-migration validator will catch silent no-ops (e.g., IF EXISTS guards
 * that swallowed a failed column rename).
 *
 * For new migrations: drop `IF EXISTS` from CHANGE COLUMN — let renames fail
 * loudly if the source column is missing. `IF NOT EXISTS` on CREATE TABLE and
 * ADD COLUMN remains fine (truly idempotent).
 *
 * @return list<SchemaAssertion>
 */
return [
    // Migration 062: dc_active → dc_canPlayInGame (caused production outage).
    // Migration 116 renamed to dc_can_play_in_game; assertions updated in-place.
    new SchemaAssertion('ibl_plr', 'dc_can_play_in_game'),
    new SchemaAssertion('ibl_saved_depth_chart_players', 'dc_can_play_in_game'),
    new SchemaAssertion('ibl_olympics_saved_depth_chart_players', 'dc_can_play_in_game'),

    // Migration 059: reserved-word renames (from → trade_from, to → trade_to)
    new SchemaAssertion('ibl_trade_info', 'trade_from'),
    new SchemaAssertion('ibl_trade_info', 'trade_to'),

    // High-usage baseline columns (referenced by many repositories)
    new SchemaAssertion('ibl_plr', 'pid'),
    new SchemaAssertion('ibl_plr', 'teamid'),
    new SchemaAssertion('ibl_plr', 'name'),
    new SchemaAssertion('ibl_team_info', 'teamid'),
    new SchemaAssertion('ibl_team_info', 'team_name'),
    new SchemaAssertion('ibl_team_info', 'gm_username'),
    new SchemaAssertion('ibl_settings', 'name'),
    new SchemaAssertion('ibl_settings', 'value'),

    // Migration 099: gm_username → gm_display_name (column stores display names, not usernames)
    new SchemaAssertion('ibl_gm_tenures', 'gm_display_name'),

    // Migration 113: reserved-word + r_to meaning-flip renames.
    // `to`/`do` were SQL reserved words (transition and drive offense ratings).
    // `r_to` previously meant turnover rating in live/snapshot tables but
    // transition-offense rating in ibl_hist (silently re-aliased by the view).
    // After the rename: r_trans_off = transition offense rating, r_drive_off =
    // drive offense rating, r_tvr = turnover rating — uniform across all layers.
    new SchemaAssertion('ibl_plr', 'r_trans_off'),
    new SchemaAssertion('ibl_plr', 'r_drive_off'),
    new SchemaAssertion('ibl_plr', 'r_tvr'),
    new SchemaAssertion('ibl_plr_snapshots', 'r_trans_off'),
    new SchemaAssertion('ibl_plr_snapshots', 'r_drive_off'),
    new SchemaAssertion('ibl_plr_snapshots', 'r_tvr'),
    new SchemaAssertion('ibl_olympics_plr', 'r_trans_off'),
    new SchemaAssertion('ibl_olympics_plr', 'r_drive_off'),
    new SchemaAssertion('ibl_olympics_plr', 'r_tvr'),
    new SchemaAssertion('ibl_draft_class', 'r_trans_off'),
    new SchemaAssertion('ibl_draft_class', 'r_drive_off'),
    new SchemaAssertion('ibl_hist', 'r_trans_off'),
    new SchemaAssertion('ibl_hist', 'r_drive_off'),
    new SchemaAssertion('ibl_olympics_hist', 'r_trans_off'),
    new SchemaAssertion('ibl_olympics_hist', 'r_drive_off'),
    new SchemaAssertion('ibl_sim_dates', 'start_date'),
    new SchemaAssertion('ibl_sim_dates', 'end_date'),

    // Migration 114: Tier 2 cross-table column-naming unification.
    // Turnovers (live layer): stats_to → stats_tvr
    new SchemaAssertion('ibl_plr', 'stats_tvr'),
    new SchemaAssertion('ibl_plr_snapshots', 'stats_tvr'),
    new SchemaAssertion('ibl_olympics_plr', 'stats_tvr'),
    // 3-pointer ratings: r_tga/r_tgp (live + olympics_plr) and bare tga/tgp
    // (ibl_draft_class) → r_3ga/r_3gp, matching ibl_hist canonical.
    new SchemaAssertion('ibl_plr', 'r_3ga'),
    new SchemaAssertion('ibl_plr', 'r_3gp'),
    new SchemaAssertion('ibl_plr_snapshots', 'r_3ga'),
    new SchemaAssertion('ibl_plr_snapshots', 'r_3gp'),
    new SchemaAssertion('ibl_olympics_plr', 'r_3ga'),
    new SchemaAssertion('ibl_olympics_plr', 'r_3gp'),
    new SchemaAssertion('ibl_draft_class', 'r_3ga'),
    new SchemaAssertion('ibl_draft_class', 'r_3gp'),
    // Team-id unified to lowercase `teamid` (or {prefix}_teamid for compounds).
    new SchemaAssertion('ibl_olympics_plr', 'teamid'),
    new SchemaAssertion('ibl_plr_snapshots', 'teamid'),
    new SchemaAssertion('ibl_draft', 'teamid'),
    new SchemaAssertion('ibl_fa_offers', 'teamid'),
    new SchemaAssertion('ibl_cash_considerations', 'teamid'),
    new SchemaAssertion('ibl_cash_considerations', 'counterparty_teamid'),
    new SchemaAssertion('ibl_standings', 'teamid'),
    new SchemaAssertion('ibl_olympics_standings', 'teamid'),
    new SchemaAssertion('ibl_saved_depth_charts', 'teamid'),
    new SchemaAssertion('ibl_olympics_saved_depth_charts', 'teamid'),
    new SchemaAssertion('ibl_plb_snapshots', 'teamid'),
    new SchemaAssertion('ibl_power', 'teamid'),
    new SchemaAssertion('ibl_olympics_power', 'teamid'),
    new SchemaAssertion('ibl_rcb_alltime_records', 'teamid'),
    new SchemaAssertion('ibl_rcb_season_records', 'teamid'),
    new SchemaAssertion('ibl_box_scores', 'teamid'),
    new SchemaAssertion('ibl_box_scores', 'home_teamid'),
    new SchemaAssertion('ibl_box_scores', 'visitor_teamid'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_teamid'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_teamid'),
    new SchemaAssertion('ibl_olympics_box_scores', 'teamid'),
    new SchemaAssertion('ibl_olympics_box_scores', 'home_teamid'),
    new SchemaAssertion('ibl_olympics_box_scores', 'visitor_teamid'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_teamid'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_teamid'),
    new SchemaAssertion('ibl_draft_picks', 'owner_teamid'),
    new SchemaAssertion('ibl_draft_picks', 'teampick_teamid'),

    // Migration 116: Tier 3a cosmetic case-consistency renames (ADR-0010).
    // Player rating columns (ibl_plr + ibl_olympics_plr; already lowercase on
    // ibl_plr_snapshots / ibl_hist).
    new SchemaAssertion('ibl_plr', 'clutch'),
    new SchemaAssertion('ibl_plr', 'consistency'),
    new SchemaAssertion('ibl_olympics_plr', 'clutch'),
    new SchemaAssertion('ibl_olympics_plr', 'consistency'),
    // Position-depth columns (ibl_plr, ibl_plr_snapshots, ibl_olympics_plr).
    new SchemaAssertion('ibl_plr', 'pg_depth'),
    new SchemaAssertion('ibl_plr', 'sg_depth'),
    new SchemaAssertion('ibl_plr', 'sf_depth'),
    new SchemaAssertion('ibl_plr', 'pf_depth'),
    new SchemaAssertion('ibl_plr', 'c_depth'),
    new SchemaAssertion('ibl_plr_snapshots', 'pg_depth'),
    new SchemaAssertion('ibl_plr_snapshots', 'sg_depth'),
    new SchemaAssertion('ibl_plr_snapshots', 'sf_depth'),
    new SchemaAssertion('ibl_plr_snapshots', 'pf_depth'),
    new SchemaAssertion('ibl_plr_snapshots', 'c_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'pg_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'sg_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'sf_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'pf_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'c_depth'),
    // Depth-chart dc_* columns (ibl_plr, ibl_olympics_plr, and both
    // ibl_*_saved_depth_chart_players tables).
    new SchemaAssertion('ibl_plr', 'dc_pg_depth'),
    new SchemaAssertion('ibl_plr', 'dc_sg_depth'),
    new SchemaAssertion('ibl_plr', 'dc_sf_depth'),
    new SchemaAssertion('ibl_plr', 'dc_pf_depth'),
    new SchemaAssertion('ibl_plr', 'dc_c_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'dc_pg_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'dc_sg_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'dc_sf_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'dc_pf_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'dc_c_depth'),
    new SchemaAssertion('ibl_olympics_plr', 'dc_can_play_in_game'),
    new SchemaAssertion('ibl_plr_snapshots', 'dc_can_play_in_game'),
    new SchemaAssertion('ibl_saved_depth_chart_players', 'dc_pg_depth'),
    new SchemaAssertion('ibl_saved_depth_chart_players', 'dc_sg_depth'),
    new SchemaAssertion('ibl_saved_depth_chart_players', 'dc_sf_depth'),
    new SchemaAssertion('ibl_saved_depth_chart_players', 'dc_pf_depth'),
    new SchemaAssertion('ibl_saved_depth_chart_players', 'dc_c_depth'),
    new SchemaAssertion('ibl_olympics_saved_depth_chart_players', 'dc_pg_depth'),
    new SchemaAssertion('ibl_olympics_saved_depth_chart_players', 'dc_sg_depth'),
    new SchemaAssertion('ibl_olympics_saved_depth_chart_players', 'dc_sf_depth'),
    new SchemaAssertion('ibl_olympics_saved_depth_chart_players', 'dc_pf_depth'),
    new SchemaAssertion('ibl_olympics_saved_depth_chart_players', 'dc_c_depth'),
    // FA pref playing_time.
    new SchemaAssertion('ibl_plr', 'playing_time'),
    new SchemaAssertion('ibl_plr_snapshots', 'playing_time'),
    new SchemaAssertion('ibl_olympics_plr', 'playing_time'),
    // sta → stamina on player + draft-class tables.
    new SchemaAssertion('ibl_plr', 'stamina'),
    new SchemaAssertion('ibl_olympics_plr', 'stamina'),
    new SchemaAssertion('ibl_draft_class', 'stamina'),
    // cache reserved-word fix.
    new SchemaAssertion('cache', 'cache_key'),
    new SchemaAssertion('cache_locks', 'cache_key'),

    // Migration 117: Tier 3b team-info column renames (ADR-0010).
    // ibl_team_info (9 columns).
    new SchemaAssertion('ibl_team_info', 'discord_id'),
    new SchemaAssertion('ibl_team_info', 'contract_wins'),
    new SchemaAssertion('ibl_team_info', 'contract_losses'),
    new SchemaAssertion('ibl_team_info', 'contract_avg_w'),
    new SchemaAssertion('ibl_team_info', 'contract_avg_l'),
    new SchemaAssertion('ibl_team_info', 'used_extension_this_chunk'),
    new SchemaAssertion('ibl_team_info', 'used_extension_this_season'),
    new SchemaAssertion('ibl_team_info', 'has_mle'),
    new SchemaAssertion('ibl_team_info', 'has_lle'),
    // ibl_olympics_team_info (5 columns).
    new SchemaAssertion('ibl_olympics_team_info', 'discord_id'),
    new SchemaAssertion('ibl_olympics_team_info', 'contract_wins'),
    new SchemaAssertion('ibl_olympics_team_info', 'contract_losses'),
    new SchemaAssertion('ibl_olympics_team_info', 'contract_avg_w'),
    new SchemaAssertion('ibl_olympics_team_info', 'contract_avg_l'),

    // Migration 118: Tier 3c standings column renames (ADR-0010).
    // ibl_standings (22 columns).
    new SchemaAssertion('ibl_standings', 'league_record'),
    new SchemaAssertion('ibl_standings', 'conf_record'),
    new SchemaAssertion('ibl_standings', 'conf_gb'),
    new SchemaAssertion('ibl_standings', 'div_record'),
    new SchemaAssertion('ibl_standings', 'div_gb'),
    new SchemaAssertion('ibl_standings', 'home_record'),
    new SchemaAssertion('ibl_standings', 'away_record'),
    new SchemaAssertion('ibl_standings', 'games_unplayed'),
    new SchemaAssertion('ibl_standings', 'conf_wins'),
    new SchemaAssertion('ibl_standings', 'conf_losses'),
    new SchemaAssertion('ibl_standings', 'div_wins'),
    new SchemaAssertion('ibl_standings', 'div_losses'),
    new SchemaAssertion('ibl_standings', 'home_wins'),
    new SchemaAssertion('ibl_standings', 'home_losses'),
    new SchemaAssertion('ibl_standings', 'away_wins'),
    new SchemaAssertion('ibl_standings', 'away_losses'),
    new SchemaAssertion('ibl_standings', 'conf_magic_number'),
    new SchemaAssertion('ibl_standings', 'div_magic_number'),
    new SchemaAssertion('ibl_standings', 'clinched_conference'),
    new SchemaAssertion('ibl_standings', 'clinched_division'),
    new SchemaAssertion('ibl_standings', 'clinched_playoffs'),
    new SchemaAssertion('ibl_standings', 'clinched_league'),
    // ibl_olympics_standings (22 columns).
    new SchemaAssertion('ibl_olympics_standings', 'league_record'),
    new SchemaAssertion('ibl_olympics_standings', 'conf_record'),
    new SchemaAssertion('ibl_olympics_standings', 'conf_gb'),
    new SchemaAssertion('ibl_olympics_standings', 'div_record'),
    new SchemaAssertion('ibl_olympics_standings', 'div_gb'),
    new SchemaAssertion('ibl_olympics_standings', 'home_record'),
    new SchemaAssertion('ibl_olympics_standings', 'away_record'),
    new SchemaAssertion('ibl_olympics_standings', 'games_unplayed'),
    new SchemaAssertion('ibl_olympics_standings', 'conf_wins'),
    new SchemaAssertion('ibl_olympics_standings', 'conf_losses'),
    new SchemaAssertion('ibl_olympics_standings', 'div_wins'),
    new SchemaAssertion('ibl_olympics_standings', 'div_losses'),
    new SchemaAssertion('ibl_olympics_standings', 'home_wins'),
    new SchemaAssertion('ibl_olympics_standings', 'home_losses'),
    new SchemaAssertion('ibl_olympics_standings', 'away_wins'),
    new SchemaAssertion('ibl_olympics_standings', 'away_losses'),
    new SchemaAssertion('ibl_olympics_standings', 'conf_magic_number'),
    new SchemaAssertion('ibl_olympics_standings', 'div_magic_number'),
    new SchemaAssertion('ibl_olympics_standings', 'clinched_conference'),
    new SchemaAssertion('ibl_olympics_standings', 'clinched_division'),
    new SchemaAssertion('ibl_olympics_standings', 'clinched_playoffs'),
    new SchemaAssertion('ibl_olympics_standings', 'clinched_league'),

    // Migration 119: Tier 4 opacity fix — cy1-cy6 → salary_yr1-salary_yr6 (ADR-0010).
    // ibl_plr (6 columns).
    new SchemaAssertion('ibl_plr', 'salary_yr1'),
    new SchemaAssertion('ibl_plr', 'salary_yr2'),
    new SchemaAssertion('ibl_plr', 'salary_yr3'),
    new SchemaAssertion('ibl_plr', 'salary_yr4'),
    new SchemaAssertion('ibl_plr', 'salary_yr5'),
    new SchemaAssertion('ibl_plr', 'salary_yr6'),
    // ibl_plr_snapshots (6 columns).
    new SchemaAssertion('ibl_plr_snapshots', 'salary_yr1'),
    new SchemaAssertion('ibl_plr_snapshots', 'salary_yr2'),
    new SchemaAssertion('ibl_plr_snapshots', 'salary_yr3'),
    new SchemaAssertion('ibl_plr_snapshots', 'salary_yr4'),
    new SchemaAssertion('ibl_plr_snapshots', 'salary_yr5'),
    new SchemaAssertion('ibl_plr_snapshots', 'salary_yr6'),
    // ibl_olympics_plr (6 columns).
    new SchemaAssertion('ibl_olympics_plr', 'salary_yr1'),
    new SchemaAssertion('ibl_olympics_plr', 'salary_yr2'),
    new SchemaAssertion('ibl_olympics_plr', 'salary_yr3'),
    new SchemaAssertion('ibl_olympics_plr', 'salary_yr4'),
    new SchemaAssertion('ibl_olympics_plr', 'salary_yr5'),
    new SchemaAssertion('ibl_olympics_plr', 'salary_yr6'),
    // ibl_cash_considerations (6 columns).
    new SchemaAssertion('ibl_cash_considerations', 'salary_yr1'),
    new SchemaAssertion('ibl_cash_considerations', 'salary_yr2'),
    new SchemaAssertion('ibl_cash_considerations', 'salary_yr3'),
    new SchemaAssertion('ibl_cash_considerations', 'salary_yr4'),
    new SchemaAssertion('ibl_cash_considerations', 'salary_yr5'),
    new SchemaAssertion('ibl_cash_considerations', 'salary_yr6'),
    // ibl_trade_cash (6 columns).
    new SchemaAssertion('ibl_trade_cash', 'salary_yr1'),
    new SchemaAssertion('ibl_trade_cash', 'salary_yr2'),
    new SchemaAssertion('ibl_trade_cash', 'salary_yr3'),
    new SchemaAssertion('ibl_trade_cash', 'salary_yr4'),
    new SchemaAssertion('ibl_trade_cash', 'salary_yr5'),
    new SchemaAssertion('ibl_trade_cash', 'salary_yr6'),
    // ibl_hist (6 columns).
    new SchemaAssertion('ibl_hist', 'salary_yr1'),
    new SchemaAssertion('ibl_hist', 'salary_yr2'),
    new SchemaAssertion('ibl_hist', 'salary_yr3'),
    new SchemaAssertion('ibl_hist', 'salary_yr4'),
    new SchemaAssertion('ibl_hist', 'salary_yr5'),
    new SchemaAssertion('ibl_hist', 'salary_yr6'),

    // Migration 120: Tier 5 misc snake_case cleanup (ADR-0010).
    // ibl_trade_cash (3 columns).
    new SchemaAssertion('ibl_trade_cash', 'trade_offer_id'),
    new SchemaAssertion('ibl_trade_cash', 'sending_team'),
    new SchemaAssertion('ibl_trade_cash', 'receiving_team'),
    // Awards tables (8 columns across 5 tables).
    new SchemaAssertion('ibl_awards', 'award'),
    new SchemaAssertion('ibl_awards', 'table_id'),
    new SchemaAssertion('ibl_gm_awards', 'award'),
    new SchemaAssertion('ibl_gm_awards', 'table_id'),
    new SchemaAssertion('ibl_gm_history', 'award'),
    new SchemaAssertion('ibl_team_awards', 'award'),
    new SchemaAssertion('ibl_team_awards', 'id'),
    new SchemaAssertion('ibl_olympics_win_loss', 'table_id'),
    // ibl_fa_offers (2 columns).
    new SchemaAssertion('ibl_fa_offers', 'mle'),
    new SchemaAssertion('ibl_fa_offers', 'lle'),
    // ibl_votes_ASG (16 ballot columns).
    new SchemaAssertion('ibl_votes_ASG', 'east_f1'),
    new SchemaAssertion('ibl_votes_ASG', 'east_f2'),
    new SchemaAssertion('ibl_votes_ASG', 'east_f3'),
    new SchemaAssertion('ibl_votes_ASG', 'east_f4'),
    new SchemaAssertion('ibl_votes_ASG', 'east_b1'),
    new SchemaAssertion('ibl_votes_ASG', 'east_b2'),
    new SchemaAssertion('ibl_votes_ASG', 'east_b3'),
    new SchemaAssertion('ibl_votes_ASG', 'east_b4'),
    new SchemaAssertion('ibl_votes_ASG', 'west_f1'),
    new SchemaAssertion('ibl_votes_ASG', 'west_f2'),
    new SchemaAssertion('ibl_votes_ASG', 'west_f3'),
    new SchemaAssertion('ibl_votes_ASG', 'west_f4'),
    new SchemaAssertion('ibl_votes_ASG', 'west_b1'),
    new SchemaAssertion('ibl_votes_ASG', 'west_b2'),
    new SchemaAssertion('ibl_votes_ASG', 'west_b3'),
    new SchemaAssertion('ibl_votes_ASG', 'west_b4'),
    // ibl_votes_EOY (12 ballot columns).
    new SchemaAssertion('ibl_votes_EOY', 'mvp_1'),
    new SchemaAssertion('ibl_votes_EOY', 'mvp_2'),
    new SchemaAssertion('ibl_votes_EOY', 'mvp_3'),
    new SchemaAssertion('ibl_votes_EOY', 'roy_1'),
    new SchemaAssertion('ibl_votes_EOY', 'roy_2'),
    new SchemaAssertion('ibl_votes_EOY', 'roy_3'),
    new SchemaAssertion('ibl_votes_EOY', 'gm_1'),
    new SchemaAssertion('ibl_votes_EOY', 'gm_2'),
    new SchemaAssertion('ibl_votes_EOY', 'gm_3'),
    new SchemaAssertion('ibl_votes_EOY', 'six_1'),
    new SchemaAssertion('ibl_votes_EOY', 'six_2'),
    new SchemaAssertion('ibl_votes_EOY', 'six_3'),
    // ibl_sim_dates Sim → sim primary key.
    new SchemaAssertion('ibl_sim_dates', 'sim'),
    // nuke_* legacy tables.
    new SchemaAssertion('nuke_config', 'censor_mode'),
    new SchemaAssertion('nuke_config', 'censor_replace'),
    new SchemaAssertion('nuke_config', 'default_theme'),
    new SchemaAssertion('nuke_config', 'version_num'),
    new SchemaAssertion('nuke_stories', 'poll_id'),

    // Migration 121: Tier 6 — box-score + schedule snake_case (ADR-0010).
    // ibl_box_scores (20 columns).
    new SchemaAssertion('ibl_box_scores', 'game_date'),
    new SchemaAssertion('ibl_box_scores', 'game_min'),
    new SchemaAssertion('ibl_box_scores', 'game_2gm'),
    new SchemaAssertion('ibl_box_scores', 'game_2ga'),
    new SchemaAssertion('ibl_box_scores', 'game_ftm'),
    new SchemaAssertion('ibl_box_scores', 'game_fta'),
    new SchemaAssertion('ibl_box_scores', 'game_3gm'),
    new SchemaAssertion('ibl_box_scores', 'game_3ga'),
    new SchemaAssertion('ibl_box_scores', 'game_orb'),
    new SchemaAssertion('ibl_box_scores', 'game_drb'),
    new SchemaAssertion('ibl_box_scores', 'game_ast'),
    new SchemaAssertion('ibl_box_scores', 'game_stl'),
    new SchemaAssertion('ibl_box_scores', 'game_tov'),
    new SchemaAssertion('ibl_box_scores', 'game_blk'),
    new SchemaAssertion('ibl_box_scores', 'game_pf'),
    new SchemaAssertion('ibl_box_scores', 'game_of_that_day'),
    new SchemaAssertion('ibl_box_scores', 'visitor_wins'),
    new SchemaAssertion('ibl_box_scores', 'visitor_losses'),
    new SchemaAssertion('ibl_box_scores', 'home_wins'),
    new SchemaAssertion('ibl_box_scores', 'home_losses'),
    // ibl_olympics_box_scores (20 columns; same set).
    new SchemaAssertion('ibl_olympics_box_scores', 'game_date'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_min'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_2gm'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_2ga'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_ftm'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_fta'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_3gm'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_3ga'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_orb'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_drb'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_ast'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_stl'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_tov'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_blk'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_pf'),
    new SchemaAssertion('ibl_olympics_box_scores', 'game_of_that_day'),
    new SchemaAssertion('ibl_olympics_box_scores', 'visitor_wins'),
    new SchemaAssertion('ibl_olympics_box_scores', 'visitor_losses'),
    new SchemaAssertion('ibl_olympics_box_scores', 'home_wins'),
    new SchemaAssertion('ibl_olympics_box_scores', 'home_losses'),
    // ibl_box_scores_teams (30 columns: 20 + 10 quarter/OT).
    new SchemaAssertion('ibl_box_scores_teams', 'game_date'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_min'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_2gm'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_2ga'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_ftm'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_fta'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_3gm'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_3ga'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_orb'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_drb'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_ast'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_stl'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_tov'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_blk'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_pf'),
    new SchemaAssertion('ibl_box_scores_teams', 'game_of_that_day'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_wins'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_losses'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_wins'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_losses'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_q1_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_q2_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_q3_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_q4_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'visitor_ot_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_q1_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_q2_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_q3_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_q4_points'),
    new SchemaAssertion('ibl_box_scores_teams', 'home_ot_points'),
    // ibl_olympics_box_scores_teams (30 columns; same set).
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_date'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_min'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_2gm'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_2ga'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_ftm'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_fta'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_3gm'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_3ga'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_orb'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_drb'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_ast'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_stl'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_tov'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_blk'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_pf'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'game_of_that_day'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_wins'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_losses'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_wins'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_losses'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_q1_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_q2_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_q3_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_q4_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'visitor_ot_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_q1_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_q2_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_q3_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_q4_points'),
    new SchemaAssertion('ibl_olympics_box_scores_teams', 'home_ot_points'),
    // ibl_schedule + ibl_olympics_schedule (8 columns each).
    new SchemaAssertion('ibl_schedule', 'id'),
    new SchemaAssertion('ibl_schedule', 'season_year'),
    new SchemaAssertion('ibl_schedule', 'box_id'),
    new SchemaAssertion('ibl_schedule', 'game_date'),
    new SchemaAssertion('ibl_schedule', 'visitor_teamid'),
    new SchemaAssertion('ibl_schedule', 'visitor_score'),
    new SchemaAssertion('ibl_schedule', 'home_teamid'),
    new SchemaAssertion('ibl_schedule', 'home_score'),
    new SchemaAssertion('ibl_olympics_schedule', 'id'),
    new SchemaAssertion('ibl_olympics_schedule', 'season_year'),
    new SchemaAssertion('ibl_olympics_schedule', 'box_id'),
    new SchemaAssertion('ibl_olympics_schedule', 'game_date'),
    new SchemaAssertion('ibl_olympics_schedule', 'visitor_teamid'),
    new SchemaAssertion('ibl_olympics_schedule', 'visitor_score'),
    new SchemaAssertion('ibl_olympics_schedule', 'home_teamid'),
    new SchemaAssertion('ibl_olympics_schedule', 'home_score'),
];
