<?php

declare(strict_types=1);

namespace PlrParser;

use PlrParser\Contracts\PlrLineParserInterface;

/**
 * Pure parser for a single 607-byte .plr player record.
 *
 * Extracted from PlrParserService so the byte-offset specification has its own
 * discoverable home, matching the JsbParser\*FileParser pattern (CarFileParser,
 * TrnFileParser, etc.). See docs/JSB_FILE_FORMATS.md for the authoritative spec.
 */
class PlrLineParser implements PlrLineParserInterface
{
    /**
     * @see PlrLineParserInterface::parse()
     */
    public static function parse(string $line): ?array
    {
        $ordinal = (int) substr($line, 0, 4);
        $pid = (int) substr($line, 38, 6);

        if ($pid === 0 || $ordinal > 1440) {
            return null;
        }

        // Extract name and convert from Windows 1252 to UTF-8 to preserve accent marks
        $nameRaw = trim(substr($line, 4, 32));
        $nameConverted = iconv('CP1252', 'UTF-8//IGNORE', $nameRaw);
        $name = $nameConverted !== false ? $nameConverted : $nameRaw;

        return [
            'ordinal' => $ordinal,
            'name' => $name,
            'age' => (int) substr($line, 36, 2),
            'pid' => $pid,
            'tid' => (int) substr($line, 44, 2),
            'peak' => (int) substr($line, 46, 4),
            'pos' => trim(substr($line, 50, 2)),
            'realLifeGP' => (int) substr($line, 52, 4),
            'realLifeMIN' => (int) substr($line, 56, 4),
            'realLifeFGM' => (int) substr($line, 60, 4),
            'realLifeFGA' => (int) substr($line, 64, 4),
            'realLifeFTM' => (int) substr($line, 68, 4),
            'realLifeFTA' => (int) substr($line, 72, 4),
            'realLife3GM' => (int) substr($line, 76, 4),
            'realLife3GA' => (int) substr($line, 80, 4),
            'realLifeORB' => (int) substr($line, 84, 4),
            'realLifeDRB' => (int) substr($line, 88, 4),
            'realLifeAST' => (int) substr($line, 92, 4),
            'realLifeSTL' => (int) substr($line, 96, 4),
            'realLifeTVR' => (int) substr($line, 100, 4),
            'realLifeBLK' => (int) substr($line, 104, 4),
            'realLifePF' => (int) substr($line, 108, 4),
            // Unknown gap: offsets 112-127 (16 bytes)
            'unk_112' => (int) substr($line, 112, 2),
            'unk_114' => (int) substr($line, 114, 2),
            'unk_116' => (int) substr($line, 116, 2),
            'unk_118' => (int) substr($line, 118, 2),
            'unk_120' => (int) substr($line, 120, 2),
            'unk_122' => (int) substr($line, 122, 2),
            'unk_124' => (int) substr($line, 124, 2),
            'unk_126' => (int) substr($line, 126, 2),
            'clutch' => (int) substr($line, 128, 2),
            'consistency' => (int) substr($line, 130, 2),
            'PGDepth' => (int) substr($line, 132, 1),
            'SGDepth' => (int) substr($line, 133, 1),
            'SFDepth' => (int) substr($line, 134, 1),
            'PFDepth' => (int) substr($line, 135, 1),
            'CDepth' => (int) substr($line, 136, 1),
            'canPlayInGame' => (int) substr($line, 137, 1),
            // Unknown gap: offset 138-139 (2 bytes)
            'unk_138' => (int) substr($line, 138, 2),
            'injuryDaysLeft' => (int) substr($line, 140, 4),
            'seasonGamesStarted' => (int) substr($line, 144, 4),
            'seasonGamesPlayed' => (int) substr($line, 148, 4),
            'seasonMIN' => (int) substr($line, 152, 4),
            'season2GM' => (int) substr($line, 156, 4),
            'season2GA' => (int) substr($line, 160, 4),
            'seasonFTM' => (int) substr($line, 164, 4),
            'seasonFTA' => (int) substr($line, 168, 4),
            'season3GM' => (int) substr($line, 172, 4),
            'season3GA' => (int) substr($line, 176, 4),
            'seasonORB' => (int) substr($line, 180, 4),
            'seasonDRB' => (int) substr($line, 184, 4),
            'seasonAST' => (int) substr($line, 188, 4),
            'seasonSTL' => (int) substr($line, 192, 4),
            'seasonTVR' => (int) substr($line, 196, 4),
            'seasonBLK' => (int) substr($line, 200, 4),
            'seasonPF' => (int) substr($line, 204, 4),
            // Playoff season stats (speculative — offsets 208-267 mirror season stats minus GS)
            'playoffSeasonGP' => (int) substr($line, 208, 4),
            'playoffSeasonMIN' => (int) substr($line, 212, 4),
            'playoffSeason2GM' => (int) substr($line, 216, 4),
            'playoffSeason2GA' => (int) substr($line, 220, 4),
            'playoffSeasonFTM' => (int) substr($line, 224, 4),
            'playoffSeasonFTA' => (int) substr($line, 228, 4),
            'playoffSeason3GM' => (int) substr($line, 232, 4),
            'playoffSeason3GA' => (int) substr($line, 236, 4),
            'playoffSeasonORB' => (int) substr($line, 240, 4),
            'playoffSeasonDRB' => (int) substr($line, 244, 4),
            'playoffSeasonAST' => (int) substr($line, 248, 4),
            'playoffSeasonSTL' => (int) substr($line, 252, 4),
            'playoffSeasonTVR' => (int) substr($line, 256, 4),
            'playoffSeasonBLK' => (int) substr($line, 260, 4),
            'playoffSeasonPF' => (int) substr($line, 264, 4),
            'talent' => (int) substr($line, 268, 2),
            'skill' => (int) substr($line, 270, 2),
            'intangibles' => (int) substr($line, 272, 2),
            'coach' => (int) substr($line, 274, 2),
            'loyalty' => (int) substr($line, 276, 2),
            'playingTime' => (int) substr($line, 278, 2),
            'playForWinner' => (int) substr($line, 280, 2),
            'tradition' => (int) substr($line, 282, 2),
            'security' => (int) substr($line, 284, 2),
            'exp' => (int) substr($line, 286, 2),
            'bird' => (int) substr($line, 288, 2),
            'currentContractYear' => (int) substr($line, 290, 2),
            'totalContractYears' => (int) substr($line, 292, 2),
            // Unknown gap: offsets 294-297 (4 bytes)
            'unk_294' => (int) substr($line, 294, 2),
            'unk_296' => (int) substr($line, 296, 2),
            'contractYear1' => (int) substr($line, 298, 4),
            'contractYear2' => (int) substr($line, 302, 4),
            'contractYear3' => (int) substr($line, 306, 4),
            'contractYear4' => (int) substr($line, 310, 4),
            'contractYear5' => (int) substr($line, 314, 4),
            'contractYear6' => (int) substr($line, 318, 4),
            // Unknown gap: offsets 322-325 (4 bytes)
            'unk_322' => (int) substr($line, 322, 2),
            'unk_324' => (int) substr($line, 324, 2),
            'draftRound' => (int) substr($line, 326, 2),
            'draftPickNumber' => (int) substr($line, 328, 2),
            'freeAgentSigningFlag' => (int) substr($line, 330, 1),
            // Unknown gap: offsets 331-340 (10 bytes)
            'unk_331' => (int) substr($line, 331, 2),
            'unk_333' => (int) substr($line, 333, 2),
            'unk_335' => (int) substr($line, 335, 2),
            'unk_337' => (int) substr($line, 337, 2),
            'unk_339' => (int) substr($line, 339, 2),
            'seasonHighPTS' => (int) substr($line, 341, 2),
            'seasonHighREB' => (int) substr($line, 343, 2),
            'seasonHighAST' => (int) substr($line, 345, 2),
            'seasonHighSTL' => (int) substr($line, 347, 2),
            'seasonHighBLK' => (int) substr($line, 349, 2),
            'seasonHighDoubleDoubles' => (int) substr($line, 351, 2),
            'seasonHighTripleDoubles' => (int) substr($line, 353, 2),
            'seasonPlayoffHighPTS' => (int) substr($line, 355, 2),
            'seasonPlayoffHighREB' => (int) substr($line, 357, 2),
            'seasonPlayoffHighAST' => (int) substr($line, 359, 2),
            'seasonPlayoffHighSTL' => (int) substr($line, 361, 2),
            'seasonPlayoffHighBLK' => (int) substr($line, 363, 2),
            'careerSeasonHighPTS' => (int) substr($line, 365, 6),
            'careerSeasonHighREB' => (int) substr($line, 371, 6),
            'careerSeasonHighAST' => (int) substr($line, 377, 6),
            'careerSeasonHighSTL' => (int) substr($line, 383, 6),
            'careerSeasonHighBLK' => (int) substr($line, 389, 6),
            'careerSeasonHighDoubleDoubles' => (int) substr($line, 395, 6),
            'careerSeasonHighTripleDoubles' => (int) substr($line, 401, 6),
            'careerPlayoffHighPTS' => (int) substr($line, 407, 6),
            'careerPlayoffHighREB' => (int) substr($line, 413, 6),
            'careerPlayoffHighAST' => (int) substr($line, 419, 6),
            'careerPlayoffHighSTL' => (int) substr($line, 425, 6),
            'careerPlayoffHighBLK' => (int) substr($line, 431, 6),
            'careerGP' => (int) substr($line, 437, 5),
            'careerMIN' => (int) substr($line, 442, 5),
            'career2GM' => (int) substr($line, 447, 5),
            'career2GA' => (int) substr($line, 452, 5),
            'careerFTM' => (int) substr($line, 457, 5),
            'careerFTA' => (int) substr($line, 462, 5),
            'career3GM' => (int) substr($line, 467, 5),
            'career3GA' => (int) substr($line, 472, 5),
            'careerORB' => (int) substr($line, 477, 5),
            'careerDRB' => (int) substr($line, 482, 5),
            'careerAST' => (int) substr($line, 487, 5),
            'careerSTL' => (int) substr($line, 492, 5),
            'careerTVR' => (int) substr($line, 497, 5),
            'careerBLK' => (int) substr($line, 502, 5),
            'careerPF' => (int) substr($line, 507, 5),
            // Unknown gap: offsets 512-549 (38 bytes)
            'unk_512' => (int) substr($line, 512, 2),
            'unk_514' => (int) substr($line, 514, 2),
            'unk_516' => (int) substr($line, 516, 2),
            'unk_518' => (int) substr($line, 518, 2),
            'unk_520' => (int) substr($line, 520, 2),
            'unk_522' => (int) substr($line, 522, 2),
            'unk_524' => (int) substr($line, 524, 2),
            'unk_526' => (int) substr($line, 526, 2),
            'unk_528' => (int) substr($line, 528, 2),
            'unk_530' => (int) substr($line, 530, 2),
            'unk_532' => (int) substr($line, 532, 2),
            'unk_534' => (int) substr($line, 534, 2),
            'unk_536' => (int) substr($line, 536, 2),
            'unk_538' => (int) substr($line, 538, 2),
            'unk_540' => (int) substr($line, 540, 2),
            'unk_542' => (int) substr($line, 542, 2),
            'unk_544' => (int) substr($line, 544, 2),
            'unk_546' => (int) substr($line, 546, 2),
            'unk_548' => (int) substr($line, 548, 2),
            'heightInches' => (int) substr($line, 550, 2),
            'weight' => (int) substr($line, 552, 3),
            'rating2GA' => (int) substr($line, 555, 3),
            'rating2GP' => (int) substr($line, 558, 3),
            'ratingFTA' => (int) substr($line, 561, 3),
            'ratingFTP' => (int) substr($line, 564, 3),
            'rating3GA' => (int) substr($line, 567, 3),
            'rating3GP' => (int) substr($line, 570, 3),
            'ratingORB' => (int) substr($line, 573, 3),
            'ratingDRB' => (int) substr($line, 576, 3),
            'ratingAST' => (int) substr($line, 579, 3),
            'ratingSTL' => (int) substr($line, 582, 3),
            'ratingTVR' => (int) substr($line, 585, 3),
            'ratingBLK' => (int) substr($line, 588, 3),
            'ratingOO' => (int) substr($line, 591, 2),
            'ratingDO' => (int) substr($line, 593, 2),
            'ratingPO' => (int) substr($line, 595, 2),
            'ratingTO' => (int) substr($line, 597, 2),
            'ratingOD' => (int) substr($line, 599, 2),
            'ratingDD' => (int) substr($line, 601, 2),
            'ratingPD' => (int) substr($line, 603, 2),
            'ratingTD' => (int) substr($line, 605, 2),
        ];
    }
}
